#!/bin/bash

CONFIG_SERVER_PASSWORD="my-password"
CONFIG_SERVER_USERNAME="my-username"
USER_SERV_REST_SERVER_PORT=8005
EUREKA_URL="my-eureka-url"
ACTIVE_PROFILE="prod"

IMAGE_NAME="user_serv"

EXTERNAL_IP=$(hostname -I | awk '{print $1}')


docker run -d -p ${USER_SERV_REST_SERVER_PORT}:${USER_SERV_REST_SERVER_PORT} \
  -e CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD} \
  -e CONFIG_SERVER_USERNAME=${CONFIG_SERVER_USERNAME} \
  -e REST_SERVER_PORT=${USER_SERV_REST_SERVER_PORT} \
  -e EUREKA_URL=${EUREKA_URL} \
  -e ACTIVE_PROFILE=${ACTIVE_PROFILE} \
  -e EXTERNAL_IP=${EXTERNAL_IP} \
  ${IMAGE_NAME}